### ISSUE TITLE
New map does not show up in map list after creation, does not appear when choosing "Reload"

### ISSUE THREAD

**Issue by MissingNoGuy55** [yenatch/crowdmap#10]
Unfortunately I don't have a log on this as it doesn't report anything, but the map I made isn't showing up in the list at all even when refreshing or restarting the server...

**Comment by yenatch** [comment]
assuming firefox, do this

http://superuser.com/questions/173210/how-can-i-clear-a-single-site-from-the-cache-in-firefox/733154#733154

once firefox has marked a file as cachable, it will never change its mind no matter what you tell it, and it won't even bother asking the server about it. this might go for chrome also

**Comment by MissingNoGuy55** [comment]
That worked, thank you.

**Comment by yenatch** [comment]
Caching issues have been fixed.
