### ISSUE TITLE
File cache does not update in response to external modifications

### ISSUE THREAD

**Issue by PikalaxALT** [yenatch/crowdmap#12]
To reproduce:
1) Open a map in Crowdmap on Google Chrome.
2) Open its script file or blockdata in an external program.
3) Modify and save the file in the external program.
4) Attempt to view the changes in Crowdmap by reloading the map.

**Comment by yenatch** [comment]
When was the first time the file was opened? If you clear the cache (browsers make this difficult to do properly), can you reproduce it with the same steps?

**Comment by PikalaxALT** [comment]
> When was the first time the file was opened?
> You mean, like ever?

**Comment by yenatch** [comment]
In crowdmap.

**Comment by PikalaxALT** [comment]
The same day the issue was first experienced (so, last Wednesday).

**Comment by yenatch** [comment]
Caching issues should be fixed now. All requests are `POST` instead of some being `GET`.
