### ISSUE TITLE
switching between inside and outside causes tileset picker to blank

### ISSUE THREAD

**Issue by PikalaxALT** [yenatch/crowdmap#4]
When switching from an outside map to an inside map or vice versa, the tileset picker graphics vanish. The side bar is still visible, but is completely black.  You can still select the tiles and place them on the map as normal.  Switching to another map of the same type (from an outdoors map to an outdoors map or from an indoors map to an indoors map) or reloading the same map will restore the tileset picker.

**Comment by yenatch** [comment]
This appears to be fixed.
